/***********************************************************
 ******************** User actionTypes *********************
 **********************************************************/
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_INIT = 'REGISTER_USER_INIT';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const PASSWORD_RESET_START = 'PASSWORD_RESET_START';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_USER_BY_ID_START = 'FETCH_USER_BY_ID_START';
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_FAIL = 'FETCH_USER_BY_ID_FAIL';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const LOGOUT_USER_ALL_START = 'LOGOUT_USER_ALL_START';
export const LOGOUT_USER_ALL_SUCCESS = 'LOGOUT_USER_ALL_SUCCESS';
export const LOGOUT_USER_ALL_FAIL = 'LOGOUT_USER_ALL_FAIL';

export const UPDATE_USER_PROFILE_START = 'UPDATE_USER_PROFILE_START';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

export const UPDATE_USER_PASSWORD_START = 'UPDATE_USER_PASSWORD_START';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAIL = 'UPDATE_USER_PASSWORD_FAIL';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const RESET_USER_ERROR = 'RESET_USER_ERROR';

/***********************************************************
 ***************** Appointment actionTypes *****************
 **********************************************************/
export const BOOK_APPOINTMENT_START = 'BOOK_APPOINTMENT_START';
export const BOOK_APPOINTMENT_SUCCESS = 'BOOK_APPOINTMENT_SUCCESS';
export const BOOK_APPOINTMENT_FAIL = 'BOOK_APPOINTMENT_FAIL';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const FETCH_APPOINTMENTS_START = 'FETCH_APPOINTMENTS_START';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENTS_FAIL = 'FETCH_APPOINTMENTS_FAIL';

export const FETCH_APPOINTMENT_BY_ID_START = 'FETCH_APPOINTMENT_BY_ID_START';
export const FETCH_APPOINTMENT_BY_ID_SUCCESS = 'FETCH_APPOINTMENT_BY_ID_SUCCESS';
export const FETCH_APPOINTMENT_BY_ID_FAIL = 'FETCH_APPOINTMENT_BY_ID_FAIL';

export const UPDATE_APPOINTMENT_BY_ID_START = 'UPDATE_APPOINTMENT_BY_ID_START';
export const UPDATE_APPOINTMENT_BY_ID_SUCCESS = 'UPDATE_APPOINTMENT_BY_ID_SUCCESS';
export const UPDATE_APPOINTMENT_BY_ID_FAIL = 'UPDATE_APPOINTMENT_BY_ID_FAIL';

export const DELETE_APPOINTMENT_BY_ID_START = 'DELETE_APPOINTMENT_BY_ID_START';
export const DELETE_APPOINTMENT_BY_ID_SUCCESS = 'DELETE_APPOINTMENT_BY_ID_SUCCESS';
export const DELETE_APPOINTMENT_BY_ID_FAIL = 'DELETE_APPOINTMENT_BY_ID_FAIL';